version: '3.0'
services:
  webpacker:
    image: ${DOCKER_IMAGE_NAME-dockerrails}
    command: ["./scripts/start_webpack_dev.sh"]
    volumes:
      - .:/opt/dockerrails:cached
    ports:
      - 3035:3035

  web:
    image: ${DOCKER_IMAGE_NAME-dockerrails}
    build:
      context: .
      args:
        precompileassets: 'no'
    links:
      - webpacker
    ports:
      - 3000:3000
    command: ["./scripts/start_rails.sh"]
    volumes:
      - .:/opt/dockerrails:cached
