default: &default
  space: kk2bw5ojx476
  access_token: 7ac531648a1b5e1dab6c18b0979f822a5aad0fe5f1109829b8a197eb2be4b84c
  environment: master
  base_url: http://cdn.contentful.com/

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  space: <%= ENV.fetch("space") { "kk2bw5ojx476" } %>
  access_token: <%= ENV.fetch("access_token") { "7ac531648a1b5e1dab6c18b0979f822a5aad0fe5f1109829b8a197eb2be4b84c" } %>
